### ISSUE TITLE
Error: No existing matlab file found, starting from scratch

### ISSUE THREAD

**Issue by mclaffey** [mclaffey/claffey_matlab#1]
Encountered by a new user of the project after running these lines in the vidz_demo script

> sub_analysis = input('Enter name of sub-analysis: ', 's');
> vid = vidz_files(video_path, sub_analysis, analysis_dir);

My reply to that user: If I'm remembering correctly, this isn't actually an error. It's just reporting that you haven't told it to use the files/directory for the previously analyzed video. It thinks that you are starting a new analysis, i.e. starting from scratch. As long as that's the case, you should be able to continue with the next lines in the script.

**Comment by RaulFrancoGL** [comment]
Nice Mike, I'm able to continue with the next lines in the script. Thanks.
